spring:
  application:
    name: portfolio-service

  data:
    mongodb:
      uri: spring.data.mongodb.uri: mongodb://192.168.50.4:27017/portfolio

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
