spring:
  application:
    name: portfolio-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/portfolio_db

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
